// Srishti AI - API Client and Simulation Engine

const API_KEYS_STORAGE_PREFIX = "srishti_api_key_";

// Helper functions to manage API keys in localStorage
function getStoredApiKey(provider) {
    return localStorage.getItem(`${API_KEYS_STORAGE_PREFIX}${provider}`) || "";
}

function setStoredApiKey(provider, key) {
    if (key.trim() === "") {
        localStorage.removeItem(`${API_KEYS_STORAGE_PREFIX}${provider}`);
    } else {
        localStorage.setItem(`${API_KEYS_STORAGE_PREFIX}${provider}`, key.trim());
    }
}

function hasAnyApiKey() {
    const providers = ["gemini", "openrouter", "openai", "anthropic", "grok", "perplexity"];
    return providers.some(p => getStoredApiKey(p) !== "");
}

// Multi-provider request router
async function callAgentAPI(agent, userPrompt, contextHistory = "") {
    const provider = agent.provider;
    const model = agent.model;
    const systemPrompt = agent.prompt;
    const apiKey = getStoredApiKey(provider);

    if (!apiKey) {
        // No key for this provider, generate context-aware simulation response
        return await generateSimulatedResponse(agent, userPrompt, contextHistory);
    }

    try {
        switch (provider) {
            case "gemini":
                return await callGeminiAPI(model, systemPrompt, userPrompt, contextHistory, apiKey);
            case "openrouter":
                return await callOpenRouterAPI(model, systemPrompt, userPrompt, contextHistory, apiKey);
            case "openai":
                return await callOpenAIAPI(model, systemPrompt, userPrompt, contextHistory, apiKey);
            case "anthropic":
                return await callAnthropicAPI(model, systemPrompt, userPrompt, contextHistory, apiKey);
            case "grok":
                return await callGrokAPI(model, systemPrompt, userPrompt, contextHistory, apiKey);
            case "perplexity":
                return await callPerplexityAPI(model, systemPrompt, userPrompt, contextHistory, apiKey);
            default:
                throw new Error(`Unknown provider: ${provider}`);
        }
    } catch (error) {
        console.warn(`API call failed for ${provider}, falling back to simulation:`, error);
        // Gracefully fall back to simulation instead of crashing the debate
        return await generateSimulatedResponse(agent, userPrompt, contextHistory);
    }
}

// 1. Google Gemini API Call
async function callGeminiAPI(model, systemPrompt, userPrompt, contextHistory, apiKey) {
    const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`;
    const promptText = `Context History of other agents' discussion:\n${contextHistory || "No previous discussion yet."}\n\nUser Question/Task:\n${userPrompt}`;
    
    const response = await fetch(url, {
        method: "POST",
        headers: {
            "Content-Type": "application/json"
        },
        body: JSON.stringify({
            contents: [
                {
                    role: "user",
                    parts: [{ text: promptText }]
                }
            ],
            systemInstruction: {
                parts: [{ text: systemPrompt }]
            },
            generationConfig: {
                temperature: 0.7,
                maxOutputTokens: 2048
            }
        })
    });

    if (!response.ok) {
        const errData = await response.json().catch(() => ({}));
        throw new Error(errData.error?.message || `HTTP ${response.status}`);
    }

    const data = await response.json();
    return data.candidates?.[0]?.content?.parts?.[0]?.text || "No response generated by Gemini.";
}

// 2. OpenRouter API Call (Supports 100% Free models)
async function callOpenRouterAPI(model, systemPrompt, userPrompt, contextHistory, apiKey) {
    const url = "https://openrouter.ai/api/v1/chat/completions";
    const promptText = `Context History of other agents' discussion:\n${contextHistory || "No previous discussion yet."}\n\nUser Question/Task:\n${userPrompt}`;

    const response = await fetch(url, {
        method: "POST",
        headers: {
            "Authorization": `Bearer ${apiKey}`,
            "Content-Type": "application/json",
            "HTTP-Referer": "https://github.com/srishti-ai", 
            "X-Title": "Srishti AI"
        },
        body: JSON.stringify({
            model: model,
            messages: [
                { role: "system", content: systemPrompt },
                { role: "user", content: promptText }
            ],
            temperature: 0.7
        })
    });

    if (!response.ok) {
        const errData = await response.json().catch(() => ({}));
        throw new Error(errData.error?.message || `HTTP ${response.status}`);
    }

    const data = await response.json();
    return data.choices?.[0]?.message?.content || "No response generated by OpenRouter.";
}

// 3. OpenAI API Call
async function callOpenAIAPI(model, systemPrompt, userPrompt, contextHistory, apiKey) {
    const url = "https://api.openai.com/v1/chat/completions";
    const promptText = `Context History of other agents' discussion:\n${contextHistory || "No previous discussion yet."}\n\nUser Question/Task:\n${userPrompt}`;

    const response = await fetch(url, {
        method: "POST",
        headers: {
            "Authorization": `Bearer ${apiKey}`,
            "Content-Type": "application/json"
        },
        body: JSON.stringify({
            model: model,
            messages: [
                { role: "system", content: systemPrompt },
                { role: "user", content: promptText }
            ],
            temperature: 0.7
        })
    });

    if (!response.ok) {
        const errData = await response.json().catch(() => ({}));
        throw new Error(errData.error?.message || `HTTP ${response.status}`);
    }

    const data = await response.json();
    return data.choices?.[0]?.message?.content || "No response generated by OpenAI.";
}

// 4. Anthropic Claude API Call (With browser CORS notice)
async function callAnthropicAPI(model, systemPrompt, userPrompt, contextHistory, apiKey) {
    const url = "https://api.anthropic.com/v1/messages";
    const promptText = `Context History of other agents' discussion:\n${contextHistory || "No previous discussion yet."}\n\nUser Question/Task:\n${userPrompt}`;

    const response = await fetch(url, {
        method: "POST",
        headers: {
            "x-api-key": apiKey,
            "anthropic-version": "2023-06-01",
            "content-type": "application/json",
            "anthropic-dangerous-direct-browser-access": "true" // Required to bypass Anthropic client warnings if they ever configure it
        },
        body: JSON.stringify({
            model: model,
            max_tokens: 2048,
            system: systemPrompt,
            messages: [
                { role: "user", content: promptText }
            ],
            temperature: 0.7
        })
    });

    if (!response.ok) {
        if (response.status === 0 || response.status === 403) {
            throw new Error("Direct Anthropic calls are blocked by CORS in web browsers. Please use OpenRouter to access Claude models client-side!");
        }
        const errData = await response.json().catch(() => ({}));
        throw new Error(errData.error?.message || `HTTP ${response.status}`);
    }

    const data = await response.json();
    return data.content?.[0]?.text || "No response generated by Claude.";
}

// 5. xAI Grok API Call
async function callGrokAPI(model, systemPrompt, userPrompt, contextHistory, apiKey) {
    const url = "https://api.x.ai/v1/chat/completions";
    const promptText = `Context History of other agents' discussion:\n${contextHistory || "No previous discussion yet."}\n\nUser Question/Task:\n${userPrompt}`;

    const response = await fetch(url, {
        method: "POST",
        headers: {
            "Authorization": `Bearer ${apiKey}`,
            "Content-Type": "application/json"
        },
        body: JSON.stringify({
            model: model,
            messages: [
                { role: "system", content: systemPrompt },
                { role: "user", content: promptText }
            ],
            temperature: 0.7
        })
    });

    if (!response.ok) {
        const errData = await response.json().catch(() => ({}));
        throw new Error(errData.error?.message || `HTTP ${response.status}`);
    }

    const data = await response.json();
    return data.choices?.[0]?.message?.content || "No response generated by Grok.";
}

// 6. Perplexity API Call
async function callPerplexityAPI(model, systemPrompt, userPrompt, contextHistory, apiKey) {
    const url = "https://api.perplexity.ai/chat/completions";
    const promptText = `Context History of other agents' discussion:\n${contextHistory || "No previous discussion yet."}\n\nUser Question/Task:\n${userPrompt}`;

    const response = await fetch(url, {
        method: "POST",
        headers: {
            "Authorization": `Bearer ${apiKey}`,
            "Content-Type": "application/json"
        },
        body: JSON.stringify({
            model: model,
            messages: [
                { role: "system", content: systemPrompt },
                { role: "user", content: promptText }
            ],
            temperature: 0.2 // Perplexity is usually better at lower temperature for factual grounding
        })
    });

    if (!response.ok) {
        const errData = await response.json().catch(() => ({}));
        throw new Error(errData.error?.message || `HTTP ${response.status}`);
    }

    const data = await response.json();
    return data.choices?.[0]?.message?.content || "No response generated by Perplexity.";
}

// ----------------------------------------------------
// Smart Context-Aware Simulation Engine (Fallback)
// ----------------------------------------------------

async function generateSimulatedResponse(agent, userPrompt, contextHistory) {
    // Artificial typing delay to simulate reasoning
    await new Promise(resolve => setTimeout(resolve, 1500 + Math.random() * 1000));

    const prompt = userPrompt.toLowerCase();
    
    // 1. Classify the user prompt
    let category = "general";
    if (/\b(code|website|html|css|js|javascript|python|java|c\+\+|bug|compile|git|api|database|sql|function|react|node|developer)\b/.test(prompt)) {
        category = "coding";
    } else if (/\b(business|marketing|product|sell|startup|customer|growth|monetize|revenue|strategy|cost|company|pitch)\b/.test(prompt)) {
        category = "business";
    } else if (/\b(write|poem|story|article|blog|essay|resume|email|copywriting|creative|character|novel)\b/.test(prompt)) {
        category = "creative";
    } else if (/\b(science|math|physics|chemical|formula|space|universe|biology|theory|research|gravity)\b/.test(prompt)) {
        category = "science";
    }

    // Extract key nouns from prompt to make the response highly specific
    const stopwords = new Set(["the", "a", "an", "and", "or", "but", "if", "then", "of", "to", "for", "with", "in", "on", "at", "by", "how", "what", "why", "where", "make", "create", "build", "write", "about", "your", "my", "me", "our", "us"]);
    const cleanedWords = userPrompt
        .replace(/[^\w\s]/g, '')
        .split(/\s+/)
        .filter(w => w.length > 2 && !stopwords.has(w.toLowerCase()));
    
    // Pick top 3-4 keywords
    const keywords = [...new Set(cleanedWords)].slice(0, 4);
    const keyTerm = keywords.join(" ") || "this problem";
    const primeTerm = keywords[0] || "solution";

    // 2. Generate agent-specific content based on role and category
    switch (agent.id) {
        case "agent-architect":
            return getArchitectSimulation(category, keyTerm, primeTerm, keywords);
        case "agent-critic":
            return getCriticSimulation(category, keyTerm, primeTerm, keywords, contextHistory);
        case "agent-search":
            return getSearchSimulation(category, keyTerm, primeTerm, keywords);
        case "agent-engineer":
            return getEngineerSimulation(category, keyTerm, primeTerm, keywords, contextHistory);
        case "agent-synthesizer":
            return getSynthesizerSimulation(category, keyTerm, primeTerm, keywords, contextHistory);
        default:
            return `### Analysis on ${keyTerm}\n\nI have reviewed the problem. Here are my thoughts:\n1. We need to define clear boundaries for ${keyTerm}.\n2. We must align this with standard best practices.\n3. Implementation details should prioritize efficiency. Let's see what the other agents think.`;
    }
}

// -- Architect simulation text generator --
function getArchitectSimulation(category, keyTerm, primeTerm, keywords) {
    if (category === "coding") {
        return `### Proposed Architecture for "${keyTerm}"

To implement **${keyTerm}** effectively, I propose a decoupled, modular design to ensure scalability, ease of testing, and separation of concerns.

#### Core Architectural Structure:
1. **Core Service Engine**: This acts as the brain. Written in idiomatic code (e.g. Node.js or Python depending on requirements), it coordinates data processing and business rules.
2. **Data Model / Store**: A clean schema containing fields for all necessary records. We'll use a relational approach (like PostgreSQL) or flat records depending on throughput requirements.
3. **API interface**: RESTful endpoints or client utility functions.
4. **Error Boundaries**: Layered handlers to capture boundary failure conditions.

\`\`\`
[ Client / UI / Entry ] 
      │  (JSON API / Request)
      ▼
[ Router & Validation ]
      │
      ▼
[ ${primeTerm.toUpperCase()} Controller ] ──(Queries)──> [ Database Store ]
      │
      ▼
[ Response Formatter ]
\`\`\`

Let's pass this to the **Security Critic** and **Search Analyst** to refine the security layout and fetch relevant libraries.`;
    }
    
    if (category === "business") {
        return `### Strategic Business Blueprint: ${keyTerm}

To approach **${keyTerm}** successfully, we must establish a strong structural methodology targeting market viability, value delivery, and scalable operations.

#### Phase 1: Value Proposition & Customer Profile
- **Primary Need**: Solve the friction point regarding ${primeTerm}.
- **Target Persona**: Modern users and businesses needing streamlined tools.
- **Value Metric**: Time saved and reduction in manual processing.

#### Phase 2: Structural Model & Funnel
1. **Acquisition (Hook)**: Offer high utility, low-friction access.
2. **Retention (Value Loop)**: Introduce recurring benefits linked directly to ${primeTerm}.
3. **Monetization Grid**: Tiered structure (Free, Pro, Enterprise).

Let's analyze the competitor space and critique any execution risks.`;
    }

    if (category === "creative") {
        return `### Creative Structure & Theme Blueprint: ${keyTerm}

For **${keyTerm}**, I recommend a structured narrative/content arch that balances emotional engagement with logical progression.

#### Theme Core:
- **Central Premise**: The journey of exploring and resolving issues with **${primeTerm}**.
- **Tone**: Professional, engaging, slightly visionary yet grounded.
- **Narrative Arc**:
  1. *The Spark / Hook*: Introduce the core conflict/topic surrounding ${primeTerm}.
  2. *The Journey / Development*: Detail the complexities, obstacles, and depth.
  3. *The Resolution*: Bring a satisfying synthesis of ideas.

Let's let the other agents evaluate this direction and check for modern references.`;
    }

    // Science / Math / General
    return `### Theoretical Framework for ${keyTerm}

To tackle **${keyTerm}**, we must establish a rigorous framework based on first principles.

#### Key Conceptual Pillars:
1. **Problem Modeling**: Representing the variables governing ${primeTerm} mathematically or logically.
2. **Constraint Definition**: Pinpointing boundary conditions and limitations.
3. **Optimization Model**: Developing a pathway to maximize efficiency and minimize error.

Let's open this up to critique from the team.`;
}

// -- Critic simulation text generator --
function getCriticSimulation(category, keyTerm, primeTerm, keywords, contextHistory) {
    const hasArchitect = contextHistory.includes("Architect");
    
    if (category === "coding") {
        return `### Critical Review: Security & Performance Concerns

I have reviewed the Lead Architect's proposal for **${keyTerm}**. While the modular layout is clean, there are several glaring vulnerabilities and bottlenecks we must address:

#### 1. Security & Injection Vectors:
* **Input Validation**: In the validation layer, we must implement strict schemas (e.g. Zod or JSON-Schema). Since this deals with **${primeTerm}**, lack of validation invites SQL injection or Remote Code Execution.
* **Authentication**: The proposal lacks mention of token validation or session security. We need standard JWT / OAuth validation.

#### 2. Performance & Scale Bottlenecks:
* **Database Queries**: If the application performs sequential DB lookups for **${keywords[1] || primeTerm}**, it will lock up under concurrent traffic. We need an indexing plan.
* **Lack of Caching**: Frequently fetched resources will overload the controller. We must inject a caching layer (like Redis) with a TTL.

#### Recommendations for the Pragmatic Engineer:
1. Wrap all controllers in global try-catch blocks.
2. Force HTTPS and implement rate-limiting (e.g., max 100 requests per minute).`;
    }

    if (category === "business") {
        return `### Risk Assessment & Viability Review

I've examined the business blueprint. It makes a few overly optimistic assumptions:

#### Key Friction Points & Vulnerabilities:
1. **High Acquisition Friction**: The proposed value loop relies on users immediately understanding ${primeTerm}. Without an extremely polished onboarding flow, bounce rates will exceed 70%.
2. **Pricing Sensitivity**: Users may not pay a premium if they can easily replicate the core benefit of ${primeTerm} using free alternatives.
3. **Execution Bottleneck**: The operational timeline lacks clear milestone deadlines, which will lead to scope creep.

#### Suggested Mitigations:
* Run a micro-validation landing page first to capture email signups before full development.
* Implement a freemium model instead of a hard paywall.`;
    }

    // Creative / Science / General
    return `### Critical Evaluation & Blindspots

The initial proposal for **${keyTerm}** is a good starting point, but it has key vulnerabilities:

1. **Assumed Consensus**: It assumes the audience/user is already fully aligned on ${primeTerm}. We need to address initial skepticism first.
2. **Logical Gaps**: There is a lack of focus on edge cases. What happens when ${primeTerm} variables go out of range or return null values?
3. **Delivery Risk**: The structure is heavy on theory but lacks immediate real-world examples. We must show, not just tell.`;
}

// -- Search Analyst simulation text generator --
function getSearchSimulation(category, keyTerm, primeTerm, keywords) {
    if (category === "coding") {
        return `### Search Report: Modern Ecosystem & Libraries

I searched current repositories and package managers for assets related to **${keyTerm}** (specifically focusing on **${primeTerm}**). Here is what we should use:

#### Recommended Packages & Tools:
1. **${primeTerm === 'python' ? 'requests + BeautifulSoup' : 'Axios + Zod'}**: For network handling and parsing. If dynamic page rendering is required, standard fetch will fail; we should use **Playwright** instead.
2. **Security Headers**: Standard practice dictates setting `helmet` middleware for Node.js backends to configure CORS, CSP, and XSS headers.
3. **Alternative APIs**: Rather than scraping raw data, my search reveals official REST endpoints are available under standard developer tiers (which are safer and respect robot.txt).

#### Industry Standards:
* Keep code structure strictly ES Modules (ESM) compliant (`import/export` instead of `require`).
* Use environment variables via `.env` files rather than hardcoding sensitive configs.`;
    }

    if (category === "business") {
        return `### Competitive Intelligence & Trend Report

I have compiled search data regarding current market trends for **${keyTerm}**:

#### Current Market Trends (2026):
* **SaaS Consolidation**: Large players are acquiring micro-tools. To stand out, Srishti AI's value proposition for ${primeTerm} must highlight a specialized, niche focus.
* **Product-Led Growth (PLG)**: 78% of top-performing startups in the ${primeTerm} space use self-serve models.
* **Open Source Alternatives**: Competitors are releasing open-source cores. We should consider a 'Core-SaaS' hybrid model to build developer trust.

#### Competitor Highlights:
* Competitor A focuses heavily on speed but lacks customer support.
* Competitor B is enterprise-only, leaving the SMB sector wide open.`;
    }

    // General / Creative / Science
    return `### Fact-Checking & Reference Analysis

I have searched reference materials and research papers regarding **${keyTerm}**:

* **State of the Art**: Current papers suggest the optimal methodology for ${primeTerm} involves iterative refinement and hybrid models.
* **Citations**: Standard datasets show a strong correlation between robust data cleansing and correct output.
* **Real-world Case Studies**: Similar projects succeeded by breaking the main goal into 3 digestible sub-milestones.`;
}

// -- Engineer simulation text generator --
function getEngineerSimulation(category, keyTerm, primeTerm, keywords, contextHistory) {
    if (category === "coding") {
        return `### Technical Implementation Details & Code

Based on the Architect's structural design, the Critic's security requirements, and the Search Analyst's recommended libraries, I have written a modular implementation for **${keyTerm}**.

Here is the robust, production-ready code snippet incorporating strict schema validation, error handling, and security practices.

\`\`\`javascript
// Srishti AI Generated Code - ${keyTerm}
import express from 'express';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';

const app = express();

// 1. Security middleware suggested by Critic & Search Analyst
app.use(helmet());
app.use(express.json());

// Rate limiting to prevent abuse
const limiter = rateLimit({
    windowMs: 15 * 60 * 1000, // 15 minutes
    max: 100, // Limit each IP to 100 requests per window
    message: { error: 'Too many requests. Please try again later.' }
});
app.use(limiter);

/**
 * Controller to handle ${primeTerm} tasks
 */
app.post('/api/${primeTerm.replace(/[^a-zA-Z0-9]/g, '')}', async (req, res) => {
    try {
        const { payload } = req.body;
        
        // Input validation guard
        if (!payload || typeof payload !== 'object') {
            return res.status(400).json({ 
                success: false, 
                error: 'Invalid input schema. Payload object is required.' 
            });
        }

        // Logic processing representing ${keyTerm}
        const result = await processTask(payload);

        res.status(200).json({
            success: true,
            timestamp: new Date().toISOString(),
            data: result
        });
    } catch (error) {
        console.error('Error executing ${primeTerm}:', error);
        res.status(500).json({ 
            success: false, 
            error: 'Internal service failure during execution.' 
        });
    }
});

async function processTask(data) {
    // Simulated core business logic
    return {
        status: 'processed',
        itemsCount: Object.keys(data).length,
        message: 'Successfully generated result for ${keyTerm}'
    };
}

export default app;
\`\`\`

#### Key Code Details:
1. **Safety First**: Implemented rate limiting and input check schemas to satisfy the Security Critic.
2. **Production-Ready**: Ready to be integrated directly into an Express gateway.`;
    }

    if (category === "business") {
        return `### Actionable Operational Roadmap

I have translated the business strategy into a concrete, phased launch plan:

#### Phase 1: Interactive Prototype (Days 1-7)
* Build a single-page interactive mockup of **${keyTerm}** with vanilla CSS/JS.
* Include a functional signup form connected directly to local storage or a free DB provider.
* Run user interviews with at least 5 target individuals.

#### Phase 2: Core Feature Build (Days 8-20)
* Deploy a minimum viable product focusing purely on the **${primeTerm}** utility.
* Avoid advanced analytics or custom settings; focus 100% on delivering the core value hook.

#### Phase 3: Launch & Metrics (Days 21-30)
* Host on a free provider (Vercel/Netlify).
* Set up a feedback loop widget directly on the main dashboard to gather real-time bug reports.`;
    }

    // Creative / General / Science
    return `### Practical Implementation Plan

Here is the operational checklist to deliver **${keyTerm}**:

1. **Preparation**: Gather all required variables for ${primeTerm}.
2. **Drafting / Prototyping**: Develop a rough draft using the outline below:
   * Define inputs clearly.
   * Format outputs in a clean structure.
   * Add a review pass for every milestone.
3. **Execution**: Start from the most difficult sub-task first to eliminate high-risk items early.`;
}

// -- Synthesizer simulation text generator --
function getSynthesizerSimulation(category, keyTerm, primeTerm, keywords, contextHistory) {
    const hasCode = contextHistory.includes("```");
    
    if (category === "coding") {
        return `# FINAL SYNTHESIS: Best Solution for ${keyTerm}

After reviewing the architectural plans, security critiques, ecosystem reports, and actual implementation details, the Srishti AI agents have reached a **consensus**. 

Here is the complete, production-ready guide to build **${keyTerm}**.

---

## 📐 System Architecture
We adopt a **Decoupled Three-Tier Architecture** consisting of an Express API gateway, a validation middleware layer, and a robust controller module. This setup isolates key functionalities and allows secure scaling.

---

## 🛡️ Security & Optimization Measures
* **Rate Limiting**: Configured to prevent brute force and DDoS vectors.
* **helmet Middleware**: Sets HTTP headers securely (CORS, CSP, X-Frame-Options).
* **Safe Parsing**: Explicitly checks the schema payload before invoking controller logic.

---

## ⚙️ Core Implementation (JavaScript ES Modules)

Save the following file as \`server.js\`. Make sure to install dependencies first:
\`\`\`bash
npm install express helmet express-rate-limit
\`\`\`

\`\`\`javascript
import express from 'express';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';

const app = express();
const PORT = process.env.PORT || 3000;

// Security Enhancements
app.use(helmet());
app.use(express.json());

// API Rate Limiter
const limiter = rateLimit({
    windowMs: 15 * 60 * 1000, 
    max: 100,
    message: { error: 'Rate limit exceeded. Please try again in a few minutes.' }
});
app.use('/api/', limiter);

// API Endpoint
app.post('/api/execute', async (req, res) => {
    try {
        const { queryData } = req.body;
        
        // Validation Guard
        if (!queryData) {
            return res.status(400).json({ 
                success: false, 
                error: 'Missing queryData parameter.' 
            });
        }
        
        // Execute clean processed logic
        const result = {
            query: queryData,
            processedAt: new Date().toISOString(),
            status: 'success',
            payload: 'Processed: ' + JSON.stringify(queryData)
        };
        
        return res.status(200).json({ success: true, result });
    } catch (err) {
        return res.status(500).json({ success: false, error: err.message });
    }
});

app.listen(PORT, () => {
    console.log(\`Srishti AI Service running on port \${PORT}\`);
});
\`\`\`

---

## 📋 Verification Checklist
1. [x] Install dependencies using \`npm install\`.
2. [x] Start the server using \`node server.js\`.
3. [x] Test via POST request using curl:
   \`\`\`bash
   curl -X POST -H "Content-Type: application/json" -d '{"queryData": "test"}' http://localhost:3000/api/execute
   \`\`\`
`;
    }

    if (category === "business") {
        return `# FINAL SYNTHESIS: Go-to-Market Strategy for "${keyTerm}"

Our collaborative agents (Architect, Critic, Search Analyst, and Engineer) have finalized the strategy for **${keyTerm}**. This plan maximizes launch speed while mitigating security, pricing, and adoption risks.

---

## 🎯 Executive Summary
We will launch **${keyTerm}** as a product-led growth (PLG) micro-SaaS targeting the friction point surrounding **${primeTerm}**. We bypass full database complexities by leveraging client-side browser caching, accelerating development time by 50%.

---

## 🗺️ Phase-by-Phase Launch Roadmap

### Phase 1: Validation & Lead Capture (Week 1)
* **Goal**: Confirm demand for ${primeTerm} before coding.
* **Action**: Launch a high-converting landing page showcasing a video mockup.
* **KPI**: Aim for >15% conversion rate on visitor-to-email signups.

### Phase 2: Single-Feature MVP (Weeks 2-3)
* **Goal**: Build and deploy the core functional engine.
* **Action**: Create a simple web app focusing *only* on resolving the user's primary pain point.
* **Hosting**: Deploy to Netlify / Vercel for instant performance.

### Phase 3: Launch & Feedback Loop (Week 4)
* **Goal**: Seed users and gather qualitative feedback.
* **Action**: Submit to ProductHunt, IndieHackers, and relevant subreddits.

---

## 🛡️ Risk & Mitigation Grid
| Risk | Severity | Mitigation |
| :--- | :--- | :--- |
| **High Churn** | Medium | Offer email summaries of user findings to stay top-of-mind. |
| **Server Overload** | Low | Shift processing entirely client-side using WebAssembly or local SDKs. |
| **Competitor Clone** | High | Focus on a unique, hyper-focused niche target group rather than general audience. |
`;
    }

    // Creative / General / Science
    return `# FINAL SYNTHESIS: Unified Solution for ${keyTerm}

This is the consensus solution developed by the Srishti AI agent team.

---

## 💡 Core Insights
1. **Define Context**: Always establish the boundaries of **${primeTerm}** before diving into details.
2. **Iterative Polish**: Build an outline, critique assumptions, and write the details step-by-step.
3. **Execution Clarity**: Keep guidelines simple, actionable, and structured.

---

## 🛠️ Action Plan
* **Step 1**: Identify key parameters related to **${keyTerm}**.
* **Step 2**: Apply the structural outlines proposed during the brainstorming sessions.
* **Step 3**: Verify outputs against the critical edge cases documented by the team.
`;
}

// Export modules if running in Node, otherwise let browser access them globally
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { getStoredApiKey, setStoredApiKey, hasAnyApiKey, callAgentAPI };
}
